app-name: fly-shortener
config:
  adminSecret:
    fromSecret: adminSecret
  googleSheetDocId:
    fromSecret: googleSheetDocId
  googleServiceAccountEmail:
    fromSecret: googleServiceAccountEmail
  googleServiceAccountKey:
    fromSecret: googleServiceAccountKey
