app-name: fly-shortener
config:
  adminSecret:
    fromSecret: adminSecret
  fallbackUrl:
    fromSecret: fallbackUrl
  googleSheetDocId:
    fromSecret: googleSheetDocId
  googleSheetRange:
    fromSecret: googleSheetRange
  googleServiceAccountEmail:
    fromSecret: googleServiceAccountEmail
  googleServiceAccountKey:
    fromSecret: googleServiceAccountKey
