app-name: fly-shortener
config:
  adminSecret:
    fromSecret: adminSecret
  fallbackUrl:
    fromSecret: fallbackUrl
  googleSheetDocId:
    fromSecret: googleSheetDocId
  googleServiceAccountEmail:
    fromSecret: googleServiceAccountEmail
  googleServiceAccountKey:
    fromSecret: googleServiceAccountKey
